version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
      time: "15:09"
      # Poland Standard Time (UTC +01:00)
      timezone: "Europe/Warsaw"
